[build]
  command = "npm run build"
  publish = ".next"
  node_version = "18.x"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max_old_space_size=4096"

[context.production.environment]
  NEXT_PUBLIC_ANALYTICS_ID = "UA-XXXXX-Y"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[dev]
  auto_launch = false
  port = 3000

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[edge_functions]
  directory = "netlify/edge-functions"